# Generated by Django 3.1.7 on 2022-09-03 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20220829_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='photo',
            field=models.CharField(default='', max_length=255),
        ),
    ]
